# Generated by Django 3.0.4 on 2020-10-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.TextField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('dobDay', models.IntegerField()),
                ('dobMon', models.TextField(max_length=3)),
                ('dobYear', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
