# Generated by Django 3.0.4 on 2020-10-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dobMon',
            field=models.TextField(max_length=10),
        ),
    ]
